# Generated by Django 5.0.2 on 2024-03-11 17:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_product_rename_posts_post'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Product',
        ),
    ]
